### ISSUE TITLE
How to link it on Windows?

### ISSUE THREAD

**Issue by puhach** [David-Haim/concurrencpp#116]
The readme provides clear instructions how to build the library, but tells nothing about linking. After compliting the building steps, I have _concurrencpp.lib_ at _C:\concurrencpp\build\lib\Release_. In Visual Studio I added the include directory _C:\concurrencpp\include_ and the library directory _C:\concurrencpp\build\lib\Release_. I specify _concurrencpp.lib_ in _Linker -> Input -> Additional Dependencies_. Trying to build a sample project results in linker errors:

![concurrentcpp-linking-errors-2](https://user-images.githubusercontent.com/12899171/226332388-bcff05c3-e3be-4328-a981-3a7ff00b6738.JPG)

**Comment by David-Haim** [comment]
Hi there!
from my experience, when VS fails to link something even though it was added as a dependency, it usually means that that library was added to just *one* configuration, and the user is trying to compile the project for another configuration.
For example, the dependency was added to Debug x86, but the user is trying to compile it for Debug x64 or Release x86.

As a first step, can we make sure the library was added (both as an include directory and a linking target) to all configurations?
thanks

**Comment by chausner** [comment]
The problem is that you are attempting to link a library built in Release mode with your application built in Debug mode. Either build both in Debug mode or both in Release mode.

**Comment by puhach** [comment]
Ok, yes, it looks like the issue was related to the configuration. But generally, is it supposed to be added to the project the way I described above?

**Comment by David-Haim** [comment]
yes, this is how you link it with VS projects.

**Comment by chausner** [comment]
Another approach is to use a package manager like vcpkg or Conan which do not require you to build the project manually. concurrencpp is available for both, although not the latest version (0.1.6) that just got released yesterday. However, I already submitted 0.1.6 to both package managers and expect it to be available soon in both package registrys.

**Comment by David-Haim** [comment]
@puhach Can I close this issue?
