### ISSUE TITLE
shared_result?

### ISSUE THREAD

**Issue by PazerOP** [David-Haim/concurrencpp#12]
Are there plans to include a "`shared_result`" type that is not move-only and allows multiple threads to `co_await` on the same result? This type would be analogous to [std::shared_future](https://en.cppreference.com/w/cpp/thread/shared_future). 

My use case is having a UI thread continuously poll an in-progress result until it is available, then using its value once it becomes available. Having to manually store the value once it becomes available significantly complicates the code on my side.

**Comment by David-Haim** [comment]
I got to say that I've never had to use `std::shared_future`, this is why I didn't even think supporting it .
It's not a bad idea but I will have to think how to implement it efficiently (and correctly on top of it). 

currently what I plan for the next month or two is more non-feature things like better tests, CI/CD. 
It's maybe possible afterwards. 

In your case, which threads beside the UI thread need to consume the value? 
Also, you can hack it around by using an atomic shared-ptr - await on the result, then set a shared pointer with the asynchronous result. each thread reads the pointer - if it's not null, the result its ready (and reference counted, which is awesome).

**Comment by PazerOP** [comment]
I should have elaborated further about my use case. The ability to wait from multiple threads is more of a secondary thing for me, the primary gain from having something like a `shared_result` is simplicity. Otherwise, to capture the full result of a `result` for multiple uses in an optimal way, you need something like `std::variant<concurrencpp::result<T>, T, std::exception_ptr>`, and you need to have code to manage that variant. 

Its just adds another layer of complexity because you have to "unpack" `result`s because you can only use them once. This same complexity doesn't exist with cppcoro's `shared_task` or C#'s `Task` types.

I could be wrong, but I think this would also mean the value type wouldn't have to be nothrow move constructible anymore?

**Comment by David-Haim** [comment]
I looked at the API of `shared_future` and basically it's just a proxy for the future - not really hard to develop. 
I'll try to push this in the following weeks, but I don't promise anything :)

**Comment by David-Haim** [comment]
Hello there.

Version 0.0.9 is being finalized and will be released in the next couple of days. 
If you're using MSVC, make sure to upgrade the compiler to version 16.8.2.
If you're using clang, make sure to upgrade to clang 11. 

Shared results are coming to the next version, 0.1.0. 
I would have added it earlier, but the library had to mature a bit, plus the pandemic and the lockdown have ironically hurt my productivity.

Happy new concurrency year!
