### ISSUE TITLE
[Enhancement] An RAII coroutine type

### ISSUE THREAD

**Issue by nofe1248** [David-Haim/concurrencpp#121]
How about adding a new coroutine type co_resource<T>?
vector<bool>'s blog post [co_resource<T>: An RAII coroutine](https://vector-of-bool.github.io/2021/12/30/co_resource.html)
Implementation of co_resource<T> in [neo_fun](https://github.com/vector-of-bool/neo-fun/blob/develop/src/neo/co_resource.hpp)

**Comment by David-Haim** [comment]
Unfortunately I have to close this for now. this is not in the scope for the near future.
