### ISSUE TITLE
typo in result.h

### ISSUE THREAD

**Issue by adks3489** [David-Haim/concurrencpp#125]
Hi,
I found typo in result.h:
https://github.com/David-Haim/concurrencpp/blob/944a65fc08b33636ac4a1bc3c6fa8e39be1f2fe1/include/concurrencpp/results/result.h#L18

https://github.com/David-Haim/concurrencpp/blob/944a65fc08b33636ac4a1bc3c6fa8e39be1f2fe1/include/concurrencpp/results/result.h#L103

I think the second part of message should be:
`<<type>> should be nothrow-move constructible or void.`

**Comment by David-Haim** [comment]
According to [wictionary](https://en.wiktionary.org/wiki/constructable#English), "constructable" is acceptable construct. non the less fixed with 215bad1da576b45f200f4027426c0ceefda8a910, because this is the spelling the standard uses.

English is sure weird.

**Comment by adks3489** [comment]
Actually I mean the 'now-throw' should be 'no throw'. I was misunderstood by the message until I see the trait.

**Comment by David-Haim** [comment]
dammit.
fixed with e86e2adf34c4bf9009460486cea67da56d336610
good catch!
