### ISSUE TITLE
Error C2039: 'numeric_limits': is not a member of 'std'

### ISSUE THREAD

**Issue by Cheney-W** [David-Haim/concurrencpp#137]
Hello, I'm a member of Microsoft VCPKG, when I built this port in an internal version of Visual Studio, it failed with following errors:
```
\include\concurrencpp/executors/constants.h(11): error C2039: 'numeric_limits': is not a member of 'std'
\include\concurrencpp/executors/constants.h(11): error C2039: 'max': is not a member of '`global namespace''
```
[STL](https://github.com/microsoft/STL) recently merged a pull request https://github.com/microsoft/STL/pull/3721, this pr reduced inclusion dependency on `<limits>` of `numeric`, resulting in the above error.
To resolve this issue, simply add `#include <limits>` to [include/concurrencpp/executors/constants.h](https://github.com/David-Haim/concurrencpp/blob/master/include/concurrencpp/executors/constants.h) in order to address it.

**Comment by David-Haim** [comment]
Fixed with f3b9c26549d4d39f36a92add2730bf09daab20b8
