### ISSUE TITLE
Works with C++ 17?

### ISSUE THREAD

**Issue by paulocoutinhox** [David-Haim/concurrencpp#143]
Hi,

I dont understand if it works with c++ 17 or only c++ 20.

Can you explain to me?

Thanks.

**Comment by jeremyong** [comment]
As per the [CMake configuration](https://github.com/David-Haim/concurrencpp/blob/master/CMakeLists.txt#L92) C++20 is a clear requirement because `<coroutine>` was introduced in C++20.

**Comment by David-Haim** [comment]
This library is built around the C++20 coroutine feature and hence cannot work properly with older versions of C++..
