### ISSUE TITLE
Singleton / Global runtime access

### ISSUE THREAD

**Issue by gotnone** [David-Haim/concurrencpp#145]
What are the pros and cons of wrapping the runtime object in a singleton or placing it into a global variable?

When initializing the runtime in main() it it my understanding that a pointer / reference to the runtime or shared pointer(s) to the executor(s) need to be passed to all objects that utilize concurrencpp tasks.

Do you have any suggestions or best practices for passing the runtime and or individual executors to objects that utilize coroutines?

**Comment by David-Haim** [comment]
Making the runtime global or a singleton is a huge anti pattern! please don't fall to this trap.
We want the runtime object to get out of scope and destruct itself in the end of main for the application to shut down gracefully - when the runtime gets out of scope it shuts down the stored executors, allowing concurrent work to stop and exit gracefully.

> When initializing the runtime in main() it it my understanding that a pointer / reference to the runtime or shared pointer(s) to the executor(s) need to be passed to all objects that utilize concurrencpp tasks.

Semi-true, concurrencpp encourages the user to pass executors as shared_ptrs down to the code flow/needed objects.
If one of your coroutines needs an executor, pass it as a parameter
If one of your objects needs an executor, pass it to it in its constructor.
Never pull an executor from inside your function from some sort of global/static instance - it's a recipe for disaster. 

The idea is to have some sort of a "real_main" function which is a coroutine, or an "application" object that contains a "run" method, then let the executors (which are reference counted) "seep down" the function/object hierarchy by passing those executors down the code flow as parameters. the application then calls "wait" on the return value of the "real_main"/"run" function - then nothing can dangle, while allowing the application to run concurrently + be shut down correctly.

I don't recommend passing the runtime object - extract what yo need from it in main, then pass it downwards to the caled functions

Schematically , I recommend the following template:

```cpp
int main(){
   runtime r;
   const auto ex0 = r.thread_pool_executor();
   const auto ex1 = r.make_manual_executor();
   const auto ex2 = r.make_worker_thread_executor();
   const auto tq = r.timer_queue(); //take whatever you need from the runtime class

   application app(ex0, ex1, ex2, tq, ....);
   auto res = app.run();

   try{
     res.wait();
   } catch( const std::exception){
    //log
   return -1;
  }
   return 0;
}


```

**Comment by gotnone** [comment]
Thanks David.  I appreciate your thoughts and suggestions.
