### ISSUE TITLE
Get the current executor inside the coroutine.

### ISSUE THREAD

**Issue by alexv-ds** [David-Haim/concurrencpp#147]
Is it possible to somehow find out inside the coroutine in which executor it was started? 

I want my coroutine to check in which executor it was started, change it if necessary, and after execution return to the executor from where it was started.

I envision it something like this:

```cpp
namespace coro = concurrencpp;

coro::result<void> async_f(uvw::loop& loop, auto new_executor /* Executor in which we will execute. */) {
  std::cout << "Hello ";
  std::cout.flush();

  auto current_executor = ... //Somehow we get the current executor.
  co_await coro::resume_on(new_executor); //change executor
  co_await async_wait(loop, 2s); //do smthing
  co_await coro::resume_on(current_executor); //going back to the executor from where we were launched.
  std::cout << "world!" << std::endl;
  co_return;
}
```

**Comment by David-Haim** [comment]
I thought about adding this feature in the future, but for now concurrencpp has no way of doing it.
You can just store the executor as a parameter and use it after `co_await` returns.

**Comment by alexv-ds** [comment]
> I thought about adding this feature in the future, but for now concurrencpp has no way of doing it. You can just store the executor as a parameter and use it after `co_await` returns.

What complications could I theoretically get if I try to implement this?

**Comment by David-Haim** [comment]
As part of a PR to the library or as sort of an adapter in your code?

**Comment by alexv-ds** [comment]
> As part of a PR to the library or as sort of an adapter in your code?

Ideally, PR.

**Comment by n0lavar** [comment]
+1 to this feature, it would be really helpful
```cpp
std::shared_ptr<concurrencpp::executor> prev_executor = co_await resume_on_thread_pool();
...
co_await resume_on(prev_executor);
```
It would be even berrer with RAII support
```cpp
{
    auto _ = co_await resume_on_thread_pool_raii();
    ...
}
```
but AFAIK we can't do it right now because cpp doesn't support async destructors

**Comment by David-Haim** [comment]
the problem with this is that every coroutine frame has to maintain a `shared_ptr` which acts as the "current executor" and every reschedule this member has to be updated. I see 3 issues with that:

* every coroutine will consume more memory
* users will have to pay for book-keeping the current executor, even if they don't use this feature
* this might break if one is mixing another (non concurrencpp) coroutine into his code 

I will again re-iterate that one can simply keep the wanted executor in the coroutine parameters/body and it won't really make the code more complicated.
