### ISSUE TITLE
Calling a coroutine in a specific executor

### ISSUE THREAD

**Issue by pefedotov** [David-Haim/concurrencpp#149]
Hello!

The suggested way to create a task to run on the executor is to use the post or submit functions, where the callable object and its parameters are passed, this can be a regular function or a lambda expression.
But what if there is some class that has coroutines as members of the class. How can I execute them on a specific executor from a regular function?

Example:

```
class TestClass
{
public:
  concurrencpp::result<int> getInt(std::string anyarg);
}

void some_function(concurrencpp::executor* executor, TestClass& test)
{
  // test.getInt("test"); 
  auto promise = executor->submit(???)
  
  // parallel getInt code.
  
  auto res = promise.get();
  // other code
}
```

**Comment by zjuwyz** [comment]
Use [Parallel coroutines](https://github.com/David-Haim/concurrencpp#parallel-coroutines)
```
#include "concurrencpp/concurrencpp.h"
#include <spdlog/spdlog.h>
#include <bits/stdc++.h>
using namespace std;
namespace co = concurrencpp;

co::result<void> test(co::executor_tag, co::executor*)
{
    spdlog::info("test start");
    this_thread::sleep_for(1s);
    spdlog::info("test stop");
    co_return;
}

int main() {
    spdlog::set_pattern("[thread %t] %+");
    spdlog::info("main start");
    co::runtime runtime;
    auto promise = test({}, runtime.thread_pool_executor().get());
    this_thread::sleep_for(0.5s);
    spdlog::info("main waiting");
    promise.get();
    spdlog::info("main stop");
}

```
outputs :

```
[thread 1198851] [2023-09-10 21:43:49.759] [info] main start
[thread 1198858] [2023-09-10 21:43:49.759] [info] test start
[thread 1198851] [2023-09-10 21:43:50.259] [info] main waiting
[thread 1198858] [2023-09-10 21:43:50.759] [info] test stop
[thread 1198851] [2023-09-10 21:43:50.759] [info] main stop
```

**Comment by zjuwyz** [comment]
1. Function pointer.  (won't work if TestClass is a virtual class)
`executor->submit(*TestClass::getInt, &test, string);`
2. Lambda wrapper
`executor->submit([this, anyarg]() -> concurrencpp::result<void> { return test.getInt(anyarg); });`

**Comment by pefedotov** [comment]
> 1. Function pointer.  (won't work if TestClass is a virtual class)
>    `executor->submit(*TestClass::getInt, &test, string);`
> 2. Lambda wrapper
>    `executor->submit([this, anyarg]() -> concurrencpp::result<void> { return test.getInt(anyarg); });`

Thanks for the answer!

The first method looks useful, but doesn't work
`executor->submit(&TestClass::getInt, &test, string)` results in compilation errors. This recording format turned out to work only for a function that does not belong to a class and has/does not have arguments, as well as for analogues of lambda expressions like `std::bind(&TestClass::getInt, &test, string)`

Unfortunately, `executor->submit` even in this case returns `concurrencpp::result<concurrencpp::result<int>>`, and not `concurrencpp::result<int>`, which would significantly simplify the code

**Comment by David-Haim** [comment]
You can wrap the method with a parallel coroutine 

```cpp

concurrencpp::result<int> getIntAsync(concurrencpp::executor_arg, std::shared_ptr<concurrencpp::executor> ex, std::string anyarg) {
  co_return co_await getInt(std::move(anyarg));
}

```

this way you guarantee that `getInt` begins to run in the wanted executor.
