### ISSUE TITLE
Add [[nodiscard]] attribute to result

### ISSUE THREAD

**Issue by arekmula** [David-Haim/concurrencpp#150]
Hi,

What do you think about adding a [[nodiscard]] attribute to the `result` class? 

```
namespace concurrencpp {
    template<class type>
    class [[nodiscard]] result {

```

```
concurrencpp::result<void> networkCall()
{
    // Do some long network call
    co_return;
}

int main() {
    concurrencpp::runtime runtime;
    networkCall(); // ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
    return 0;
}
```

I know that this would kinda break the API and basically all the API consumers can do it by their own by marking the functions as [[nodiscard]]. However the reason for that change is that for most of the use cases you don't want to ignore the result of the coroutine, because you need to consume the result of it to make sure that it finished or throw some exception. 

With this change if someone wants to ignore the result of the coroutine he would need to do it explicitly with `std::ignore`.

I know that it still doesn't solve all the issues because you can still forget to await/get on the result, but at least eliminates some of the issues and rises the awarness of the developers.

In the developement process of our product we had an issue that somebody didn't mark the function as a nodiscard and then later on forgot to consume the result of the function which caused some bug.

**Comment by David-Haim** [comment]
You are correct. I should add [[nodiscard]] to *many* of the library classes
I've written it down for future addition to the library 
thank you!
