### ISSUE TITLE
SetThreadDescription not available on Windows 7

### ISSUE THREAD

**Issue by Polarhigh** [David-Haim/concurrencpp#152]
Hi!
I am facing a problem that my application is not working on windows 7. There seems to be no other problems besides SetThreadDescription (if I comment out the SetThreadDescription call in thread.cpp, everything runs).
So, could you add windows 7 support to concurrencpp?

![image](https://github.com/David-Haim/concurrencpp/assets/4231922/94a221bf-c4ff-4e53-9c45-bd454af4a433)

**Comment by David-Haim** [comment]
Sorry, concurrencpp is supported on Windows 10 and above.
You might want to know that windows 7 has reached end-of-life and even Microsoft doesn't support it anymore.
