### ISSUE TITLE
constexpr function must be initialized

### ISSUE THREAD

**Issue by jurschreuder** [David-Haim/concurrencpp#36]
Disclaimer: I am very new to C++, so I'm probably doing something stupid.

When I try to build concurrencpp with:
`mkdir build`
`cd build`
`cmake build ..`
`cmake --build .`

I get an error:

```
concurrencpp/include/concurrencpp/task.h:119:20: error: variables defined in a constexpr function must be initialized
void(*move_fn)(viud* src, void* dst) noexcept;
```

**Comment by David-Haim** [comment]
Interesting. 
What compiler do you use, and what version?

**Comment by jurschreuder** [comment]
clang 7.0.1-8+rpi3+deb10u2

**Comment by David-Haim** [comment]
I see.
the library is only supported with clang 11, so I guess this is why I've never got this error message

does the error reproduce with clang11?

**Comment by jurschreuder** [comment]
Thanx! That worked!

Line 14 in `concurrencpp/cmake/coroutineOptions.cmake` has to be made case-insensitive however, quick fix.
```
string( TOLOWER ${CMAKE_CXX_COMPILER_ID}" compiler_id )
if( compiler_id MATCHES "clang" )
```

Noob install guide:

Installed clang11 for raspberry pi binary (also other pre-built binaries available) form:
[https://releases.llvm.org/download.html#11.0.0](https://releases.llvm.org/download.html#11.0.0)
extract
rename folder to clang_11.0.0
move to: /usr/local/clang_11.0.0
export PATH=/usr/local/clang_11.0.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/clang_11.0.0/lib:$LD_LIBRARY_PATH

change line 14 in `concurrencpp/cmake/coroutineOptions.cmake` from
`    if(CMAKE_CXX_COMPILER_ID MATCHES "CLANG")`
`    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")`

`mkdir concurrencpp/build`
`cd concurrencpp/build`
`cmake ..`
`cmake --build .`
`cmake --install . --config Debug`

**Comment by David-Haim** [comment]
it's a good thing you're using the library on Raspberry pi , as I don't posses any raspberry machine.
I guess this is why I haven't encountered those problems yet.

feel free to report more problems you find, this knowledge is very valuable.  I will add that small change to the next release. 
Thanks.
