### ISSUE TITLE
why accumulator is not empty in executor.h

### ISSUE THREAD

**Issue by yockie** [David-Haim/concurrencpp#41]
hi, I am learning the source code of concurrencpp now，but I have a question about do_bulk_submit implement in executor.h：
do_bulk_submit invoke bulk_submit_bridge for several times，and bulk_submit_bridge implement is simple that has not modified accumulator:
```
template<class callable_type, class return_type = typename std::invoke_result_t<callable_type>>
        static result<return_type> bulk_submit_bridge(details::executor_bulk_tag,
                                                      std::vector<concurrencpp::task>& accumulator,
                                                      callable_type callable) {
            co_return callable();
        }
```

 So why accumulator is not empty after invoking bulk_submit_bridge in do_bulk_submit ？
```
for (auto& callable : callable_list) {
                results.emplace_back(bulk_submit_bridge<callable_type>({}, accumulator, std::move(callable)));
            }

            assert(!accumulator.empty());
```

I would be sincerely grateful if you could respond. Thanks.

**Comment by David-Haim** [comment]
Hi there, and thank you for taking interest in concurrencpp.
When a bulk coroutine is launched, a [bulk_promise](https://github.com/David-Haim/concurrencpp/blob/master/include/concurrencpp/results/promises.h#L93) is created behind the scenes, and the accumulator is stored in a thread-local variable.
then when [initially suspending each coroutine](https://github.com/David-Haim/concurrencpp/blob/master/include/concurrencpp/results/promises.h#L97) , each coroutine handle is [pushed into the vector](https://github.com/David-Haim/concurrencpp/blob/master/source/results/promises.cpp#L16).

And this is why the accumulator is not empty.
Remember, when you dissect a corotuine, you must dissect its coroutine-promise to see the whole picture.
