### ISSUE TITLE
Does concurrencpp have to build by clang11 and above?

### ISSUE THREAD

**Issue by Mirocos** [David-Haim/concurrencpp#44]
I tried to build this project in my macos 10.14 with clang-10.
Error happened like this, does this is a error cause by clang-10?
```bash
concurrencpp/include/concurrencpp/task.h:92:20: error: variables defined in a constexpr function
      must be initialized
            void (*move_destroy_fn)(void* src, void* dst) noexcept;
                   ^
1 error generated.
make[2]: *** [CMakeFiles/concurrencpp.dir/source/task.cpp.o] Error 1
make[1]: *** [CMakeFiles/concurrencpp.dir/all] Error 2

```

**Comment by David-Haim** [comment]
Hi there
This problem has been solved, currently not merged to master yet. 

A new version is coming either this weekend or next week, containing the fix. meanwhile, you can checkout develop branch and work with it.
