### ISSUE TITLE
Compile error in use

### ISSUE THREAD

**Issue by yezilaoda** [David-Haim/concurrencpp#56]
Version: newest
OS: Win10
IDE:VS2019 newest

when i compile my project with this lib

concurrencpp\results\when_result.h(135,76): warning C4003: 类函数宏的调用“max”参数不足
concurrencpp\results\when_result.h(135,76): error C2589: “(”:“::”右边的非法标记

code is

auto completed_result_index = std::numeric_limits<size_t>::max();

**Comment by David-Haim** [comment]
Hi
I'm not familiar with Chinese, so I can only guess what's the problem. 
My guess is that something is defining `max` before you include `concurrenncpp.h`. `Windows.h` is a regular suspect. 

What happens if you add `#undef max` right before you include concurrencpp's headers in your code?

**Comment by David-Haim** [comment]
Any new?

**Comment by yezilaoda** [comment]
thanks

**Comment by yezilaoda** [comment]
It was solved
