### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by ghost** [David-Haim/concurrencpp#57]
Hi,

Linux; Debian Bullseye;

I tried to compile with 
`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++-11 -S . -B build/lib`
The first step works
but 
`cmake --build build/lib `

fails with so many errors. For ex:
`error: ‘coroutine_handle’ does not name a type; did you mean ‘coroutine_handle_functor’`
`error: expected ‘)’ before ‘<’ token coroutine_handle_functor(coroutine_handle<void> coro_handle) noexcept : m_coro_handle(coro_handle) {}`
`error: class ‘concurrencpp::details::coroutine_handle_functor’ does not have any field named ‘m_coro_handle’`

Same with GCC 11. I changed the filecoroutineOptions to

```
function(target_coroutine_options TARGET)
  if(MSVC)
    target_compile_options(${TARGET} PUBLIC /std:c++latest /permissive-)
    return()
  endif()

  find_package(Threads REQUIRED)
  target_link_libraries(${TARGET} PRIVATE Threads::Threads)

  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    target_compile_options(${TARGET} PUBLIC -std=libc++-fcoroutines-ts)
    target_link_options(${TARGET} PUBLIC -std=libc++)
    set_target_properties(${TARGET} PROPERTIES CXX_EXTENSIONS NO)
    
elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    target_compile_options(${TARGET} PUBLIC -std=gnu++20 -fcoroutines)
    target_link_options(${TARGET} PUBLIC -std=gnu++20)
    set_target_properties(${TARGET} PROPERTIES CXX_EXTENSIONS NO)
  else()
    message(FATAL_ERROR "Compiler not supported: ${CMAKE_CXX_COMPILER_ID}")
  endif()
endfunction()
```
That library really seems good but, as of now, cannot compile it. Before looking further I would like your opinion on this.
I don't get why the code is not working given recent compilers and gnu++20 or clang c11.

Thanks :)

**Comment by ghost** [comment]
So,

I finally got it to compile on GCC11:

`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER="/path/to/g++" -DCMAKE_CXX_FLAGS="-fpermissive" -S . -B build/lib`

And appended to the coroutine.h:
```
#elif defined(CRCPP_GCC_COMPILER)

#    include <coroutine>

namespace concurrencpp::details {
    template<class promise_type>
    using coroutine_handle = std::coroutine_handle<promise_type>;
    using suspend_never = std::suspend_never;
    using suspend_always = std::suspend_always;
}  // namespace concurrencpp::details
#endif
```

But I think we need to agree that the -permissive flag is a no go. The problem is a redundancy of specialization:

`specialization of ‘template<class _Result, class ...> struct std::__n4861::coroutine_traits’ in different namespace`
in concurrencpp/include/concurrencpp/results/impl/shared_result_state.h:159:12

It is the experimental namespace that make all that fuss..

**Comment by David-Haim** [comment]
Hi there.
GCC is not supported at all at this stage. 
the clang error looks weird, can you paste the compiler output entirely? I'll look at it.

**Comment by ghost** [comment]
I made it compile fine this morning on GCC 11. We just need the permissive flag and adding the snippet above.

**Comment by David-Haim** [comment]
Again, GCC is not supported :) 
I'm interested in the clang error.
Does it still reproduce?
