### ISSUE TITLE
关于 co_await 关键字 在VS 2019 上报错的问题    An issue about the co_await keyword reporting an error on VS 2019

### ISSUE THREAD

**Issue by RAVER0306** [David-Haim/concurrencpp#59]
你好,我想知道为什么 awaitable_base  它的拷贝构造函数为什么要delete
还有 awaitable_base 它的移动构造函数为什么也要delete

当我去实现它们,错误就没了

Hi, I was wondering why awaitable_base why does its copy constructor delete

And awaitable_base why does its move constructor delete as well

When I implement them, the mistakes go away

**Comment by David-Haim** [comment]
Hi there.
can you please add a minimal example that make the error message appear?

**Comment by David-Haim** [comment]
Any new?
