### ISSUE TITLE
MSVC support with CMake project

### ISSUE THREAD

**Issue by PazerOP** [David-Haim/concurrencpp#6]
Currently this library does not support MSVC. Are there plans to add support?

**Comment by David-Haim** [comment]
Hi there.
The library is supported on MSVC, It requires Visual Studio 2019 and Windows 10 and above.
Did you try to open the main concurrencpp.sln and try to compile it? It should work.

David.

**Comment by PazerOP** [comment]
Ah, I didn't notice the .sln, and that does compile properly. While I can use that in the meantime, it would also be nice if the CMake version was usable on MSVC as well, since I use Visual Studio's CMake support with a project of mine that I'm looking into using your library with.

It doesn't seem like it'd be too much work to add support for it, so I might look into making a pull request in the near future. 

Unrelated question: are you actually using any CMake features from 3.18? It would also be useful if the minimum CMake version was relaxed a bit, at least to 3.17.

**Comment by David-Haim** [comment]
>> It doesn't seem like it'd be too much work to add support for it, so I might look into making a pull request in the near future.

Awesome. I planned doing it someday in the near future - drop all sln/vcxproj files and support MSVC with CMAKE only. I tried to do it, but it wasn't as trivial as I thought, and there are more important things at the moment. 
If you want to help there, you're more than welcome.

>> It would also be useful if the minimum CMake version was relaxed a bit, at least to 3.17.

I don't mind as long as nothing breaks. I plan to push a new version the next days, I might add it as a last minute feature.

**Comment by David-Haim** [comment]
Merged.
