### ISSUE TITLE
why  remove await_via？

### ISSUE THREAD

**Issue by xleo-gogo** [David-Haim/concurrencpp#63]
Thanks for  offering us such a amazing tool. But I meet some problem when I want to upgrade latest version.  I think  result::await_via is very useful when you want  the coroutine  resume execute in a specific thread. And my work is heavy depend on this feature. Hope you add this feature back, otherwise I must add this manually every time I fetch your new code.

**Comment by David-Haim** [comment]
Hello there.
The reason it was removed is the addition of `resume_on` which makes it redundant. 

Instead of writing `auto value = co_await result.await_via(executor)` you can write instead 
```cpp
auto value = co_await result;
co_await resume_on(executor);
``` 

you can even implement your own `await_via` as a free-standing function:

```cpp
template<class type>
type await_via(result<type>& result, std::shared_ptr<executor>){
 auto done_result = co_await result.resolve();
 co_await resume_on(executor);
 co_return co_await done_result; 
}
```
