### ISSUE TITLE
Cancellation support

### ISSUE THREAD

**Issue by rodrigovaras** [David-Haim/concurrencpp#69]
We are looking for a solid solution when using C++ 20 for async tasks and be able to project into other languages,
The library API looks very nice except for the lack of cancellation support, this will impact when attempting to project the API into C# where the cancellation pattern is a must.

**Comment by david-haim-sentinelone** [comment]
Hi!

There is some cancellation support in concurrencpp (like `timer::cancel` and `executor::shutdown`). concurrencpp doesn't actually support that many utilities that require cancellation (like asynchronous IO for example). 
For co-operative "general" task cancellation you can use the standard `std::stop_token`, which is designed after C# `CancellationToken`, Then you can tell another ongoing task to abort, and query the cancellation state in that ongoing task.

David.

**Comment by David-Haim** [comment]
Hi!

There is some cancellation support in concurrencpp (like `timer::cancel` and `executor::shutdown`). concurrencpp doesn't actually support that many utilities that require cancellation (like asynchronous IO for example).
For co-operative "general" task cancellation you can use the standard `std::stop_token`, which is designed after C# `CancellationToken`, Then you can tell another ongoing task to abort, and query the cancellation state in that ongoing task.

David.
