### ISSUE TITLE
gcc support  ?

### ISSUE THREAD

**Issue by Maziar123** [David-Haim/concurrencpp#72]
Hi

Have this lib support gcc (gcc 10.2 ? gcc 11 ?)   ?

**Comment by ktrout1111** [comment]
Apparently not

```
  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    target_compile_options(${TARGET} PUBLIC -stdlib=libc++ -fcoroutines-ts)
    target_link_options(${TARGET} PUBLIC -stdlib=libc++)
    set_target_properties(${TARGET} PROPERTIES CXX_EXTENSIONS NO)
  else()
    message(FATAL_ERROR "Compiler not supported: ${CMAKE_CXX_COMPILER_ID}")
  endif()
```

**Comment by Maziar123** [comment]
can give me why not support gcc 11 have fully corutine support ...

**Comment by David-Haim** [comment]
Hello there.
GCC still produces buggy assembly code for coroutines, and their implementation is still not mature enough for production level coroutine code. 
Hence GCC is still not supported.
Hopefully with GCC 13 they will fix most of their bugs and concurrencpp could be used with GCC.

**Comment by Maziar123** [comment]
> GCC still produces buggy assembly code for coroutines

have evidence foryour comment ?

https://gcc.gnu.org/bugzilla/buglist.cgi?quicksearch=Coroutine

seems lower  confirm bug as msvc now !

**Comment by chausner** [comment]
> have evidence foryour comment ?

I can confirm gcc 12 still has issues, see https://github.com/David-Haim/concurrencpp/pull/51#issuecomment-1104517207.

**Comment by Maziar123** [comment]
> > have evidence foryour comment ?
> 
> I can confirm gcc 12 still has issues, see [#51 (comment)](https://github.com/David-Haim/concurrencpp/pull/51#issuecomment-1104517207).

I don't see any issues represented by GCC pr stdlib
this bug in build

**Comment by chausner** [comment]
> I don't see any issues represented by GCC pr stdlib this bug in build

I think it compiles fine with the adaptations in https://github.com/David-Haim/concurrencpp/pull/51 but the unit tests fail due to some errors that are due to bugs in the coroutine implementation in GCC, according to @David-Haim.

**Comment by Maziar123** [comment]
But my quick check #51  show this is not happened via GCC

This is a bug in code for cross-platform compatibility …
