### ISSUE TITLE
/usr/bin/ld: cannot find -lpthreads

### ISSUE THREAD

**Issue by uuuuu-diwu** [David-Haim/concurrencpp#80]
CMake Error at cmake/coroutineOptions.cmake:18 (message):
  Compiler not supported: GNU
Call Stack (most recent call first):
  CMakeLists.txt:92 (target_coroutine_options)

i only have libpthread.a and libpthread.so in /usr/lib/x86_64-linux-gnu/

**Comment by chausner** [comment]
> Compiler not supported: GNU

This indicates you are attempting to build the library using GCC. Only Clang and MSVC compilers are currently supported.

**Comment by David-Haim** [comment]
As @chausner has already said, GCC is not supported at the momemt, and in my opinion, still not production ready when it comes to coroutines.

Thank you for using concurrencpp
