### ISSUE TITLE
process result asynchronously when cannot co_await result

### ISSUE THREAD

**Issue by 5fuheyan** [David-Haim/concurrencpp#82]
Sometimes it's not possible to co_await a result , but we also want to process the result asynchronously. Maybe result object can provides a then() member function that allows the caller to provide a custom continuation callback to be invoked when the coroutine finishes.

**Comment by David-Haim** [comment]
You can do it manually with `null_result` and self-invoking lambda.

```cpp

result<int> res = some_coro();

[res = std::move(res)]() -> null_result {
   auto int_result = co_await res;
  // do something with int_result
}();

```

In the days of async/await, `then` is an archaic pattern that was used in the old days of callbacks.
