### ISSUE TITLE
Thread pool executor errors when shutdown occurs before max idle time.

### ISSUE THREAD

**Issue by ohanar** [David-Haim/concurrencpp#93]
After spinning up a task on the thread pool executor, if following its completion, the thread pool is shutdown before the max idle time expires, you get the following failed assertion (in debug builds):
`Assertion failed: m_idle, file ...\concurrencpp\source\executors\thread_pool_executor.cpp, line 130`

**Comment by David-Haim** [comment]
Can you please post a minimal-reproducing example?
thanks!

**Comment by ohanar** [comment]
Okay, it ended up being a little more complicated, and seems to be Windows specific. Namely, it occurs if the executor is managed in a dll, and used in an exe (or probably also in a different dll). Here is the code:

```c++
// lib.cxx
#include <concurrencpp/concurrencpp.h>

namespace {
    struct Executor {
        concurrencpp::thread_pool_executor inner;

        template<class... T>
        constexpr Executor(T&&... args) : inner {std::forward<T>(args)...} {}
        ~Executor() noexcept {
            this->inner.shutdown();
        }
    };
}  // namespace

#ifdef _WIN32
__declspec(dllexport)
#endif
auto getExecutor() -> std::shared_ptr<concurrencpp::thread_pool_executor> {
    using namespace std::literals;
    static auto pool = std::make_shared<Executor>("", 1, 1s);
    return {pool, &pool->inner};
}
```
```c++
// main.cxx
#include <concurrencpp/concurrencpp.h>

#ifdef _WIN32
__declspec(dllimport)
#endif
auto getExecutor() -> std::shared_ptr<concurrencpp::thread_pool_executor>;

auto main() -> int {
    getExecutor()
        ->submit([] {
        })
        .get();
    return 0;
}
```
```cmake
# CMakeLists.txt
add_library(testlib SHARED lib.cxx)
target_link_libraries(testlib PUBLIC concurrencpp)

add_executable(testexe main.cxx)
target_link_libraries(testexe PRIVATE testlib)
```

**Comment by David-Haim** [comment]
> Namely, it occurs if the executor is managed in a dll, and used in an exe (or probably also in a different dll).

It's not a valid usage of the library, all user-made executors must be created using `runtime::make_executor`, as the documentation says:

> New executors can be created using runtime::make_executor. Applications must not create new executors with plain instantiation (such as std::make_shared or plain new), only by using runtime::make_executor. 

The runtime must be created in the first lines of `main` : 

> concurrencpp is built around the RAII concept. In order to use tasks and executors, applications create a runtime instance in the beginning of the main function.

The idea is to create a runtime in the beginning of main, then let the executors "seep down" the code flow by passing it as arguments to coroutines. when main finishes, the executors are joined along all running tasks. 

Two more issues from this code:
* executors must inherit from `derivable_executor`
* no need to call `executor::shutdown`, the runtime does it in its destructor

**Comment by ohanar** [comment]
> > Namely, it occurs if the executor is managed in a dll, and used in an exe (or probably also in a different dll).
> 
> It's not a valid usage of the library, all user-made executors must be created using `runtime::make_executor`, as the documentation says:

Sure, this is not strictly necessary. We could use this instead:
```c++
// lib.cxx
#include <concurrencpp/concurrencpp.h>

#ifdef _WIN32
__declspec(dllexport)
#endif
auto getExecutor() -> std::shared_ptr<concurrencpp::thread_pool_executor> {
    static auto runtime = concurrencpp::runtime {};
    return runtime.thread_pool_executor();
}
```
It results in the same issue.

> 
> The runtime must be created in the first lines of `main` :
> 
> > concurrencpp is built around the RAII concept. In order to use tasks and executors, applications create a runtime instance in the beginning of the main function.
> 
> The idea is to create a runtime in the beginning of main, then let the executors "seep down" the code flow by passing it as arguments to coroutines. when main finishes, the executors are joined along all running tasks.

I'm familiar with the concept, and that is fine in the case of writing an application (i.e. something that has a main), but it doesn't work when writing a library. Even if I never constructed a runtime or executor in my own library, and required dependents to pass executors to me, it still wouldn't work for my situation, as I need to expose my library as plugins for other programming languages (so there is literally no main that could hold the runtime).

Anyways, I'm pretty sure this issue is closely tied to #75. Specifically, because concurrencpp can't be used as a shared library on Windows, both the dll and the exe are statically linking the library, and so therefor have their own instances of the thread_local variables, causing things to break. I'll see about putting together a PR in the next couple of days that properly handles exporting symbols on Windows.

**Comment by David-Haim** [comment]
>  but it doesn't work when writing a library

It will if it's linked statically :) 

> Anyways, I'm pretty sure this issue is closely tied to https://github.com/David-Haim/concurrencpp/issues/75.

I agree. it boils down to when you try to link concurrencpp dynamically on Windows. 
I'm closing this ticket now, looking forward for the fix of it. 

Thanks again for all the effort!
