### ISSUE TITLE
Can I start multiple timer queues in different threads?

### ISSUE THREAD

**Issue by frameworker2019** [David-Haim/concurrencpp#99]
From the doc:
> A timer queue is a concurrencpp worker that manages a collection of timers and processes them in just one thread of execution. 

I'm new in C++ and the whole topic of multithreading programming technics, so I'm trying to learn here. I have a project whose primary intention is not to split a task into several pieces and working on a common result set. 
Instead I have hundreds of tasks which must be executed in a regular manner like the timer queue.
Probably not the main intention of this library.
From my point of view it would be wise to chunk the whole thing similar to the example in the doc [here](https://github.com/David-Haim/concurrencpp#concurrent-even-number-counting) but I'm struggling with the understanding of the executor concept.

What happens exactly when I call make_timer() multiple times from main() for example like this:
```
 runtime.timer_queue()->
                make_timer(
                           100ms + std::chrono::milliseconds(i),
                           1000ms,
                           runtime.background_executor(),
                           &Operator::run, o)
                        );
```

The time queue is bound to one thread and all timers are coroutines which are supended/resumed by the timer queue itself according their frequencies. 
And all timer are executed inside the same thread the timer queue is using, right?

How can I achieve to bind multiple timer queues to different threads, how would a code example looks like?

**Comment by David-Haim** [comment]
Hello there.
This is not exactly how the timer queue works.
The timer queue is an internal concurrencpp worker that has the sole responsibility of managing deadlines and frequencies. 
The timer queue itself does not run any callable - when it's time for the timer to be shot, the timer queue schedules the callable to run using the given executor. the timer queue is not bound to any specific executor. it just iterates stored timers and fires them by scheduling their callables to run in their appropriate executors. 

So, it's not like the timer queue is a bound to a specific executor - it's the timers themselves that are bound. every timer is bound to an executor that is passed in its constructor. the timer queue uses this executor to run the timer callable.
Three different timers can have three different executors passed in their constructor - the timer queue runs on a thread of its own, then when it's time for a timer to be shot the timer queue pulls the timer callable and executor and schedules the callable to run on that executor.

**Comment by frameworker2019** [comment]
Okay, understood so far.
